// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FocusEnvelope.proto

#ifndef PROTOBUF_FocusEnvelope_2eproto__INCLUDED
#define PROTOBUF_FocusEnvelope_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "FocusEvent.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_FocusEnvelope_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsEnvelopeImpl();
void InitDefaultsEnvelope();
inline void InitDefaults() {
  InitDefaultsEnvelope();
}
}  // namespace protobuf_FocusEnvelope_2eproto
namespace Focus {
class Envelope;
class EnvelopeDefaultTypeInternal;
extern EnvelopeDefaultTypeInternal _Envelope_default_instance_;
}  // namespace Focus
namespace Focus {

// ===================================================================

class Envelope : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Focus.Envelope) */ {
 public:
  Envelope();
  virtual ~Envelope();

  Envelope(const Envelope& from);

  inline Envelope& operator=(const Envelope& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Envelope(Envelope&& from) noexcept
    : Envelope() {
    *this = ::std::move(from);
  }

  inline Envelope& operator=(Envelope&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Envelope& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Envelope* internal_default_instance() {
    return reinterpret_cast<const Envelope*>(
               &_Envelope_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Envelope* other);
  friend void swap(Envelope& a, Envelope& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Envelope* New() const PROTOBUF_FINAL { return New(NULL); }

  Envelope* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Envelope& from);
  void MergeFrom(const Envelope& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Envelope* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Focus.Event events = 2;
  int events_size() const;
  void clear_events();
  static const int kEventsFieldNumber = 2;
  const ::Focus::Event& events(int index) const;
  ::Focus::Event* mutable_events(int index);
  ::Focus::Event* add_events();
  ::google::protobuf::RepeatedPtrField< ::Focus::Event >*
      mutable_events();
  const ::google::protobuf::RepeatedPtrField< ::Focus::Event >&
      events() const;

  // string clientID = 1;
  void clear_clientid();
  static const int kClientIDFieldNumber = 1;
  const ::std::string& clientid() const;
  void set_clientid(const ::std::string& value);
  #if LANG_CXX11
  void set_clientid(::std::string&& value);
  #endif
  void set_clientid(const char* value);
  void set_clientid(const char* value, size_t size);
  ::std::string* mutable_clientid();
  ::std::string* release_clientid();
  void set_allocated_clientid(::std::string* clientid);

  // @@protoc_insertion_point(class_scope:Focus.Envelope)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Focus::Event > events_;
  ::google::protobuf::internal::ArenaStringPtr clientid_;
  mutable int _cached_size_;
  friend struct ::protobuf_FocusEnvelope_2eproto::TableStruct;
  friend void ::protobuf_FocusEnvelope_2eproto::InitDefaultsEnvelopeImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Envelope

// string clientID = 1;
inline void Envelope::clear_clientid() {
  clientid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Envelope::clientid() const {
  // @@protoc_insertion_point(field_get:Focus.Envelope.clientID)
  return clientid_.GetNoArena();
}
inline void Envelope::set_clientid(const ::std::string& value) {
  
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Focus.Envelope.clientID)
}
#if LANG_CXX11
inline void Envelope::set_clientid(::std::string&& value) {
  
  clientid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Focus.Envelope.clientID)
}
#endif
inline void Envelope::set_clientid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Focus.Envelope.clientID)
}
inline void Envelope::set_clientid(const char* value, size_t size) {
  
  clientid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Focus.Envelope.clientID)
}
inline ::std::string* Envelope::mutable_clientid() {
  
  // @@protoc_insertion_point(field_mutable:Focus.Envelope.clientID)
  return clientid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Envelope::release_clientid() {
  // @@protoc_insertion_point(field_release:Focus.Envelope.clientID)
  
  return clientid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Envelope::set_allocated_clientid(::std::string* clientid) {
  if (clientid != NULL) {
    
  } else {
    
  }
  clientid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), clientid);
  // @@protoc_insertion_point(field_set_allocated:Focus.Envelope.clientID)
}

// repeated .Focus.Event events = 2;
inline int Envelope::events_size() const {
  return events_.size();
}
inline const ::Focus::Event& Envelope::events(int index) const {
  // @@protoc_insertion_point(field_get:Focus.Envelope.events)
  return events_.Get(index);
}
inline ::Focus::Event* Envelope::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:Focus.Envelope.events)
  return events_.Mutable(index);
}
inline ::Focus::Event* Envelope::add_events() {
  // @@protoc_insertion_point(field_add:Focus.Envelope.events)
  return events_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Focus::Event >*
Envelope::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:Focus.Envelope.events)
  return &events_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Focus::Event >&
Envelope::events() const {
  // @@protoc_insertion_point(field_list:Focus.Envelope.events)
  return events_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Focus

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_FocusEnvelope_2eproto__INCLUDED
