// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FocusKeyEventPayload.proto

#include "FocusKeyEventPayload.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace Focus {
class KeyEventPayloadDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KeyEventPayload>
      _instance;
} _KeyEventPayload_default_instance_;
}  // namespace Focus
namespace protobuf_FocusKeyEventPayload_2eproto {
void InitDefaultsKeyEventPayloadImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Focus::_KeyEventPayload_default_instance_;
    new (ptr) ::Focus::KeyEventPayload();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Focus::KeyEventPayload::InitAsDefaultInstance();
}

void InitDefaultsKeyEventPayload() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsKeyEventPayloadImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Focus::KeyEventPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Focus::KeyEventPayload, plaintextkeylog_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Focus::KeyEventPayload)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Focus::_KeyEventPayload_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "FocusKeyEventPayload.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032FocusKeyEventPayload.proto\022\005Focus\"*\n\017K"
      "eyEventPayload\022\027\n\017PlainTextKeylog\030\001 \001(\014b"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 87);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FocusKeyEventPayload.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_FocusKeyEventPayload_2eproto
namespace Focus {

// ===================================================================

void KeyEventPayload::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KeyEventPayload::kPlainTextKeylogFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KeyEventPayload::KeyEventPayload()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FocusKeyEventPayload_2eproto::InitDefaultsKeyEventPayload();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Focus.KeyEventPayload)
}
KeyEventPayload::KeyEventPayload(const KeyEventPayload& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  plaintextkeylog_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.plaintextkeylog().size() > 0) {
    plaintextkeylog_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.plaintextkeylog_);
  }
  // @@protoc_insertion_point(copy_constructor:Focus.KeyEventPayload)
}

void KeyEventPayload::SharedCtor() {
  plaintextkeylog_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

KeyEventPayload::~KeyEventPayload() {
  // @@protoc_insertion_point(destructor:Focus.KeyEventPayload)
  SharedDtor();
}

void KeyEventPayload::SharedDtor() {
  plaintextkeylog_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void KeyEventPayload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KeyEventPayload::descriptor() {
  ::protobuf_FocusKeyEventPayload_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FocusKeyEventPayload_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const KeyEventPayload& KeyEventPayload::default_instance() {
  ::protobuf_FocusKeyEventPayload_2eproto::InitDefaultsKeyEventPayload();
  return *internal_default_instance();
}

KeyEventPayload* KeyEventPayload::New(::google::protobuf::Arena* arena) const {
  KeyEventPayload* n = new KeyEventPayload;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void KeyEventPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:Focus.KeyEventPayload)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  plaintextkeylog_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool KeyEventPayload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Focus.KeyEventPayload)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes PlainTextKeylog = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_plaintextkeylog()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Focus.KeyEventPayload)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Focus.KeyEventPayload)
  return false;
#undef DO_
}

void KeyEventPayload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Focus.KeyEventPayload)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes PlainTextKeylog = 1;
  if (this->plaintextkeylog().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->plaintextkeylog(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Focus.KeyEventPayload)
}

::google::protobuf::uint8* KeyEventPayload::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Focus.KeyEventPayload)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes PlainTextKeylog = 1;
  if (this->plaintextkeylog().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->plaintextkeylog(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Focus.KeyEventPayload)
  return target;
}

size_t KeyEventPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Focus.KeyEventPayload)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes PlainTextKeylog = 1;
  if (this->plaintextkeylog().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->plaintextkeylog());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KeyEventPayload::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Focus.KeyEventPayload)
  GOOGLE_DCHECK_NE(&from, this);
  const KeyEventPayload* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KeyEventPayload>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Focus.KeyEventPayload)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Focus.KeyEventPayload)
    MergeFrom(*source);
  }
}

void KeyEventPayload::MergeFrom(const KeyEventPayload& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Focus.KeyEventPayload)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.plaintextkeylog().size() > 0) {

    plaintextkeylog_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.plaintextkeylog_);
  }
}

void KeyEventPayload::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Focus.KeyEventPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KeyEventPayload::CopyFrom(const KeyEventPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Focus.KeyEventPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KeyEventPayload::IsInitialized() const {
  return true;
}

void KeyEventPayload::Swap(KeyEventPayload* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KeyEventPayload::InternalSwap(KeyEventPayload* other) {
  using std::swap;
  plaintextkeylog_.Swap(&other->plaintextkeylog_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata KeyEventPayload::GetMetadata() const {
  protobuf_FocusKeyEventPayload_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FocusKeyEventPayload_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Focus

// @@protoc_insertion_point(global_scope)
