// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FocusContextEventPayload.proto

#ifndef PROTOBUF_FocusContextEventPayload_2eproto__INCLUDED
#define PROTOBUF_FocusContextEventPayload_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_FocusContextEventPayload_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsContextEventPayloadImpl();
void InitDefaultsContextEventPayload();
inline void InitDefaults() {
  InitDefaultsContextEventPayload();
}
}  // namespace protobuf_FocusContextEventPayload_2eproto
namespace Focus {
class ContextEventPayload;
class ContextEventPayloadDefaultTypeInternal;
extern ContextEventPayloadDefaultTypeInternal _ContextEventPayload_default_instance_;
}  // namespace Focus
namespace Focus {

// ===================================================================

class ContextEventPayload : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Focus.ContextEventPayload) */ {
 public:
  ContextEventPayload();
  virtual ~ContextEventPayload();

  ContextEventPayload(const ContextEventPayload& from);

  inline ContextEventPayload& operator=(const ContextEventPayload& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ContextEventPayload(ContextEventPayload&& from) noexcept
    : ContextEventPayload() {
    *this = ::std::move(from);
  }

  inline ContextEventPayload& operator=(ContextEventPayload&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ContextEventPayload& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ContextEventPayload* internal_default_instance() {
    return reinterpret_cast<const ContextEventPayload*>(
               &_ContextEventPayload_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ContextEventPayload* other);
  friend void swap(ContextEventPayload& a, ContextEventPayload& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ContextEventPayload* New() const PROTOBUF_FINAL { return New(NULL); }

  ContextEventPayload* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ContextEventPayload& from);
  void MergeFrom(const ContextEventPayload& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ContextEventPayload* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes ProcessName = 1;
  void clear_processname();
  static const int kProcessNameFieldNumber = 1;
  const ::std::string& processname() const;
  void set_processname(const ::std::string& value);
  #if LANG_CXX11
  void set_processname(::std::string&& value);
  #endif
  void set_processname(const char* value);
  void set_processname(const void* value, size_t size);
  ::std::string* mutable_processname();
  ::std::string* release_processname();
  void set_allocated_processname(::std::string* processname);

  // bytes WindowName = 2;
  void clear_windowname();
  static const int kWindowNameFieldNumber = 2;
  const ::std::string& windowname() const;
  void set_windowname(const ::std::string& value);
  #if LANG_CXX11
  void set_windowname(::std::string&& value);
  #endif
  void set_windowname(const char* value);
  void set_windowname(const void* value, size_t size);
  ::std::string* mutable_windowname();
  ::std::string* release_windowname();
  void set_allocated_windowname(::std::string* windowname);

  // @@protoc_insertion_point(class_scope:Focus.ContextEventPayload)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr processname_;
  ::google::protobuf::internal::ArenaStringPtr windowname_;
  mutable int _cached_size_;
  friend struct ::protobuf_FocusContextEventPayload_2eproto::TableStruct;
  friend void ::protobuf_FocusContextEventPayload_2eproto::InitDefaultsContextEventPayloadImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ContextEventPayload

// bytes ProcessName = 1;
inline void ContextEventPayload::clear_processname() {
  processname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ContextEventPayload::processname() const {
  // @@protoc_insertion_point(field_get:Focus.ContextEventPayload.ProcessName)
  return processname_.GetNoArena();
}
inline void ContextEventPayload::set_processname(const ::std::string& value) {
  
  processname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Focus.ContextEventPayload.ProcessName)
}
#if LANG_CXX11
inline void ContextEventPayload::set_processname(::std::string&& value) {
  
  processname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Focus.ContextEventPayload.ProcessName)
}
#endif
inline void ContextEventPayload::set_processname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  processname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Focus.ContextEventPayload.ProcessName)
}
inline void ContextEventPayload::set_processname(const void* value, size_t size) {
  
  processname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Focus.ContextEventPayload.ProcessName)
}
inline ::std::string* ContextEventPayload::mutable_processname() {
  
  // @@protoc_insertion_point(field_mutable:Focus.ContextEventPayload.ProcessName)
  return processname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ContextEventPayload::release_processname() {
  // @@protoc_insertion_point(field_release:Focus.ContextEventPayload.ProcessName)
  
  return processname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContextEventPayload::set_allocated_processname(::std::string* processname) {
  if (processname != NULL) {
    
  } else {
    
  }
  processname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), processname);
  // @@protoc_insertion_point(field_set_allocated:Focus.ContextEventPayload.ProcessName)
}

// bytes WindowName = 2;
inline void ContextEventPayload::clear_windowname() {
  windowname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ContextEventPayload::windowname() const {
  // @@protoc_insertion_point(field_get:Focus.ContextEventPayload.WindowName)
  return windowname_.GetNoArena();
}
inline void ContextEventPayload::set_windowname(const ::std::string& value) {
  
  windowname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Focus.ContextEventPayload.WindowName)
}
#if LANG_CXX11
inline void ContextEventPayload::set_windowname(::std::string&& value) {
  
  windowname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Focus.ContextEventPayload.WindowName)
}
#endif
inline void ContextEventPayload::set_windowname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  windowname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Focus.ContextEventPayload.WindowName)
}
inline void ContextEventPayload::set_windowname(const void* value, size_t size) {
  
  windowname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Focus.ContextEventPayload.WindowName)
}
inline ::std::string* ContextEventPayload::mutable_windowname() {
  
  // @@protoc_insertion_point(field_mutable:Focus.ContextEventPayload.WindowName)
  return windowname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ContextEventPayload::release_windowname() {
  // @@protoc_insertion_point(field_release:Focus.ContextEventPayload.WindowName)
  
  return windowname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContextEventPayload::set_allocated_windowname(::std::string* windowname) {
  if (windowname != NULL) {
    
  } else {
    
  }
  windowname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), windowname);
  // @@protoc_insertion_point(field_set_allocated:Focus.ContextEventPayload.WindowName)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Focus

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_FocusContextEventPayload_2eproto__INCLUDED
