// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FocusContextEventPayload.proto

#include "FocusContextEventPayload.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace Focus {
class ContextEventPayloadDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ContextEventPayload>
      _instance;
} _ContextEventPayload_default_instance_;
}  // namespace Focus
namespace protobuf_FocusContextEventPayload_2eproto {
void InitDefaultsContextEventPayloadImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Focus::_ContextEventPayload_default_instance_;
    new (ptr) ::Focus::ContextEventPayload();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Focus::ContextEventPayload::InitAsDefaultInstance();
}

void InitDefaultsContextEventPayload() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsContextEventPayloadImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Focus::ContextEventPayload, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Focus::ContextEventPayload, processname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Focus::ContextEventPayload, windowname_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Focus::ContextEventPayload)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Focus::_ContextEventPayload_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "FocusContextEventPayload.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\036FocusContextEventPayload.proto\022\005Focus\""
      ">\n\023ContextEventPayload\022\023\n\013ProcessName\030\001 "
      "\001(\014\022\022\n\nWindowName\030\002 \001(\014b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 111);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FocusContextEventPayload.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_FocusContextEventPayload_2eproto
namespace Focus {

// ===================================================================

void ContextEventPayload::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ContextEventPayload::kProcessNameFieldNumber;
const int ContextEventPayload::kWindowNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ContextEventPayload::ContextEventPayload()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FocusContextEventPayload_2eproto::InitDefaultsContextEventPayload();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Focus.ContextEventPayload)
}
ContextEventPayload::ContextEventPayload(const ContextEventPayload& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  processname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.processname().size() > 0) {
    processname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.processname_);
  }
  windowname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.windowname().size() > 0) {
    windowname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.windowname_);
  }
  // @@protoc_insertion_point(copy_constructor:Focus.ContextEventPayload)
}

void ContextEventPayload::SharedCtor() {
  processname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  windowname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

ContextEventPayload::~ContextEventPayload() {
  // @@protoc_insertion_point(destructor:Focus.ContextEventPayload)
  SharedDtor();
}

void ContextEventPayload::SharedDtor() {
  processname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  windowname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ContextEventPayload::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ContextEventPayload::descriptor() {
  ::protobuf_FocusContextEventPayload_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FocusContextEventPayload_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ContextEventPayload& ContextEventPayload::default_instance() {
  ::protobuf_FocusContextEventPayload_2eproto::InitDefaultsContextEventPayload();
  return *internal_default_instance();
}

ContextEventPayload* ContextEventPayload::New(::google::protobuf::Arena* arena) const {
  ContextEventPayload* n = new ContextEventPayload;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ContextEventPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:Focus.ContextEventPayload)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  processname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  windowname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ContextEventPayload::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Focus.ContextEventPayload)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes ProcessName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_processname()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes WindowName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_windowname()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Focus.ContextEventPayload)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Focus.ContextEventPayload)
  return false;
#undef DO_
}

void ContextEventPayload::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Focus.ContextEventPayload)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes ProcessName = 1;
  if (this->processname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->processname(), output);
  }

  // bytes WindowName = 2;
  if (this->windowname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->windowname(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Focus.ContextEventPayload)
}

::google::protobuf::uint8* ContextEventPayload::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Focus.ContextEventPayload)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes ProcessName = 1;
  if (this->processname().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->processname(), target);
  }

  // bytes WindowName = 2;
  if (this->windowname().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->windowname(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Focus.ContextEventPayload)
  return target;
}

size_t ContextEventPayload::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Focus.ContextEventPayload)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes ProcessName = 1;
  if (this->processname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->processname());
  }

  // bytes WindowName = 2;
  if (this->windowname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->windowname());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ContextEventPayload::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Focus.ContextEventPayload)
  GOOGLE_DCHECK_NE(&from, this);
  const ContextEventPayload* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ContextEventPayload>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Focus.ContextEventPayload)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Focus.ContextEventPayload)
    MergeFrom(*source);
  }
}

void ContextEventPayload::MergeFrom(const ContextEventPayload& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Focus.ContextEventPayload)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.processname().size() > 0) {

    processname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.processname_);
  }
  if (from.windowname().size() > 0) {

    windowname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.windowname_);
  }
}

void ContextEventPayload::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Focus.ContextEventPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ContextEventPayload::CopyFrom(const ContextEventPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Focus.ContextEventPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContextEventPayload::IsInitialized() const {
  return true;
}

void ContextEventPayload::Swap(ContextEventPayload* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ContextEventPayload::InternalSwap(ContextEventPayload* other) {
  using std::swap;
  processname_.Swap(&other->processname_);
  windowname_.Swap(&other->windowname_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ContextEventPayload::GetMetadata() const {
  protobuf_FocusContextEventPayload_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FocusContextEventPayload_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Focus

// @@protoc_insertion_point(global_scope)
