os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\daemon

cache:
  - C:\projects\daemon\protobuf-3.5.0\
  - C:\projects\daemon\libzmq-4.2.3\
  - C:\projects\daemon\jwt-cpp\

install:
  - CALL appveyor_protobuf.bat
  - CALL appveyor_jwt-cpp.bat
  - CALL appveyor_zmq.bat

platform:
  - x86
configuration:
  - Debug

build:
  project: daemon.sln

before_build:
  - echo [COMPILING PROTO FILES]
  - cd c:\projects\daemon\Shared\Proto
  - CALL generate.bat
  - echo [RUNNING CMAKE]
  - cd c:\projects\daemon
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=%P%

after_build:
  - echo Running Unit Tests...
  - ctest -C Debug --verbose
