clone_folder: C:\projects\daemon

cache: C:\tools\vcpkg\installed\

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
    VCVARSALL_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build'
    ADDITIONAL_CMAKE_ARGS: '-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake'
    CONFIGURATION: Release
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GENERATOR: 'Visual Studio 15 2017'
    VCVARSALL_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build'
    ADDITIONAL_CMAKE_ARGS: '-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake'
    CONFIGURATION: Release

before_build:
  - echo [VCPKG]
  - cd c:\tools\vcpkg
  - vcpkg integrate install
  - vcpkg install protobuf:x86-windows
  - vcpkg install protobuf:x64-windows
  - vcpkg install openssl:x86-windows
  - vcpkg install openssl:x64-windows
  - vcpkg install zeromq:x86-windows
  - vcpkg install zeromq:x64-windows
  - echo [GIT SUBMODULE]
  - cd C:\projects\daemon
  - git submodule update --init --recursive

build_script:
  - cmake -G "%CMAKE_GENERATOR%" . -DCMAKE_BUILD_TYPE=%CONFIGURATION% %ADDITIONAL_CMAKE_ARGS%
  - msbuild /P:Configuration=Release ALL_BUILD.vcxproj

after_build:
  - echo Running Unit Tests...
  - ctest -C Debug --verbose
  - msbuild /P:Configuration=Release PACKAGE.vcxproj
