os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\daemon

install:
  - curl -L -o protobuf.zip https://github.com/google/protobuf/releases/download/v3.5.0/protobuf-all-3.5.0.zip
  - 7z x protobuf.zip
  - del /Q protobuf.zip
  - CALL appveyor_protobuf.bat

platform:
  - Win32
configuration:
  - Release

build:
  project: daemon.sln

before_build:
  - echo [RUNNING CMAKE]
  - cd c:\projects\daemon
  - cmake -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX=%P%

after_build:
  - echo Running Unit Tests...
  - ctest -C Release --verbose