os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\daemon

cache: c:\tools\vcpkg\installed\

install:
  - vcpkg install protobuf:x64-windows-static

platform:
  - Win32
configuration:
  - Release

build:
  project: daemon.sln

before_build:
  - C:/Tools/vcpkg/packages/protobuf_x64-windows-static/tools/protoc.exe --cpp_out=./Shared/Proto/ProtoCompiled ./Shared/Proto/FocusEnvelope.proto
  - echo [RUNNING CMAKE]
  - cd c:\projects\daemon
  - cmake -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX=%P% -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static

after_build:
  - echo Running Unit Tests...
  - ctest -C Release --verbose